### PR TITLE
最簡單的範例像這樣

### PR DESCRIPTION
**Pull request by KennethKinLum**
不用 "看起來"

### CODE REVIEW

**Comment by neighborhood999** [comment]
Hi @KennethKinLum, thank you for helping, can you use English as commit message?

**Comment by KennethKinLum** [comment]
> Hi @KennethKinLum, thank you for helping, can you use English as commit message?

oh you mean... in general, use Chinese for translation, but use English for GitHub comments and subject line and content?

**Comment by neighborhood999** [comment]
> > Hi @KennethKinLum, thank you for helping, can you use English as commit message?
> 
> oh you mean... in general, use Chinese for translation, but use English for GitHub comments and subject line and content?

因為前面大家都是一致的使用英文作為 commit message & PR title，所以我覺得可以遵循這個慣例，讓 commit message 看起來比較一致，而不是中英文參雜。

**Comment by jianlin** [comment]
> > > Hi @KennethKinLum, thank you for helping, can you use English as commit message?
> > 
> > 
> > oh you mean... in general, use Chinese for translation, but use English for GitHub comments and subject line and content?
> 
> 因為前面大家都是一致的使用英文作為 commit message & PR title，所以我覺得可以遵循這個慣例，讓 commit message 看起來比較一致，而不是中英文參雜。

謝謝指點。請問閣下在台灣做 programmer？難找工作嗎？我也想住台灣和在台灣做 programmer 或教 programming 不過目前沒有在台灣工作證

**Comment by KennethKinLum** [comment]
> > > Hi @KennethKinLum, thank you for helping, can you use English as commit message?
> > 
> > 
> > oh you mean... in general, use Chinese for translation, but use English for GitHub comments and subject line and content?
> 
> 因為前面大家都是一致的使用英文作為 commit message & PR title，所以我覺得可以遵循這個慣例，讓 commit message 看起來比較一致，而不是中英文參雜。

謝謝指點。請問閣下在台灣做 programmer？難找工作嗎？我也想住台灣和在台灣做 programmer 或教 programming 不過目前沒有在台灣工作證

**Comment by chloewlin** [comment]
> > > > Hi @KennethKinLum, thank you for helping, can you use English as commit message?
> > > 
> > > 
> > > oh you mean... in general, use Chinese for translation, but use English for GitHub comments and subject line and content?
> > 
> > 
> > 因為前面大家都是一致的使用英文作為 commit message & PR title，所以我覺得可以遵循這個慣例，讓 commit message 看起來比較一致，而不是中英文參雜。
> 
> 謝謝指點。請問閣下在台灣做 programmer？難找工作嗎？我也想住台灣和在台灣做 programmer 或教 programming 不過目前沒有在台灣工作證

Hey @KennethKinLum, thank you for your suggestion. We like to keep translation as colloquial as possible, so I don't see a problem keeping it as it is.

Your questions about finding a job as a programmer in Taiwan is irrelevant to this PR. I suggest that you go to job search websites for more informations on work visa. Thank you.

**Comment by KennethKinLum** [comment]
> > > > > Hi @KennethKinLum, thank you for helping, can you use English as commit message?
> > > > 
> > > > 
> > > > oh you mean... in general, use Chinese for translation, but use English for GitHub comments and subject line and content?
> > > 
> > > 
> > > 因為前面大家都是一致的使用英文作為 commit message & PR title，所以我覺得可以遵循這個慣例，讓 commit message 看起來比較一致，而不是中英文參雜。
> > 
> > 
> > 謝謝指點。請問閣下在台灣做 programmer？難找工作嗎？我也想住台灣和在台灣做 programmer 或教 programming 不過目前沒有在台灣工作證
> 
> Hey @KennethKinLum, thank you for your suggestion. We like to keep translation as colloquial as possible, so I don't see a problem keeping it as it is.
> 
> Your questions about finding a job as a programmer in Taiwan is irrelevant to this PR. I suggest that you go to job search websites for more informations on work visa. Thank you.

again, here, "最簡單的範例看起來像是", the phrase "看起來像是" means "when you look at it, it looks like".  You use it in situation such as "the person looks as if he hasn't eaten for a few years" or "the small rabbit looks as if it is a small mouse". You don't say, 最簡單的範例看起來像是, "The simplest example looks as if it is like this". Nobody ever says that in Chinese.

**Pull request closed without merging**
