### PR TITLE
docs(hooks): remove invisible characters

### PR DESCRIPTION
**Pull request by lithiumpie**
Remove invisible characters U+001C, U+0008. Characters will show in Window 10 Machine.

### CODE REVIEW

**Comment by neighborhood999** [comment]
Hi @lithiumpie, thank you for contribution.

Can you snapshot this problem on your machine(Win 10), I just want to confirm, Thanks!

**Comment by lithiumpie** [comment]
unicode
unicode2
unicode3

**Comment by neighborhood999** [comment]
> unicode
> 
> unicode2
> 
> unicode3

That's weird haha, thanks for helping.

**Comment by lithiumpie** [comment]
@neighborhood999  Hi, Do we still have problems of merging?

**Comment by neighborhood999** [comment]
> @neighborhood999 Hi, Do we still have problems of merging?

Sorry, I forgot this PR, Thank you!

**Pull request merged**
