### PR TITLE
synthetic translation

### PR DESCRIPTION
**Pull request by KennethKinLum**
synthetic translation could be better as "virtual" or "man-made" 人造

### CODE REVIEW

**Comment by neighborhood999** [comment]
或許可以直接保留原文

**Comment by chloewlin** [comment]
我也傾向保持原文，因為人造只是 synthetic 的其中一個意思

**Comment by KennethKinLum** [comment]
> 我也傾向保持原文，因為人造只是 synthetic 的其中一個意思

but 綜合 means "comprehensive", meaning "many facets" or varieties, such as 綜合節目，meaning it is a program of a variety of entertainments.  So it is outright wrong.  Synthetic here does not mean "variety" or "comprehensive", it means "man made".  Why would we want to put here a wrong translation?

**Comment by itszero** [comment]
Sorry for passing by comments.

I'm wondering if we were to translate the term 擬似事件 or something similar would be closer to what it is conveying -- man made yes but more importantly, mirrors the actual DOM event interface. 人造 does not quiet convey the same meaning here.

I also agree the other option is to keep it untranslated.

**Comment by KennethKinLum** [comment]
> 擬似事件

means emulated or simulated event...  isn't synthetic in the original text meaning, "it is not a native JavaScript event, but is an event object that is 'made' to look like one"? So that's why I called it a manmade event or 人造事件.  

I thought the suggestion here is keep it as 綜合事件?   Or does it mean to keep it as "Synthetic 事件"?

**Comment by chloewlin** [comment]
@KennethKinLum thank you for your response. You are right, the original translation 綜合 is confusing, which is why you are motivated to submit this PR. Good job. :) 

I think we can either (1) keep it as "synthetic" in English, or (2) create a new vocabulary, such as 擬似, that sounds technical enough and can convey the concept of this technology. 

Like you said, the conventional translation for "synthetic" is 人造, but that is usually referring to a material or a product. This is a technical documentation, and the conventional translation does not seem suitable. Perhaps the best way to approach this is: which translation can help developers quickly understand this technology? 

I think @itszero 's proposal, 擬似, is a great idea. It accurately captures the essence of a synthetic event: it is not the native JavaScript event fired by the browser but an event that looks like it. It also sounds technical and easy to memorize. 

When translating technical documentation, one of our goals is to set up standards for future developers. Thank you for helping us find this glitch.

If this sounds good, let's change it to 擬似事件 then? :)

**Comment by KennethKinLum** [comment]
> @KennethKinLum thank you for your response. You are right, the original translation 綜合 is confusing, which is why you are motivated to submit this PR. Good job. :)
> 
> I think we can either (1) keep it as "synthetic" in English, or (2) create a new vocabulary, such as 擬似, that sounds technical enough and can convey the concept of this technology.
> 
> Like you said, the conventional translation for "synthetic" is 人造, but that is usually referring to a material or a product. This is a technical documentation, and the conventional translation does not seem suitable. Perhaps the best way to approach this is: which translation can help developers quickly understand this technology?
> 
> I think @itszero 's proposal, 擬似, is a great idea. It accurately captures the essence of a synthetic event: it is not the native JavaScript event fired by the browser but an event that looks like it. It also sounds technical and easy to memorize.
> 
> When translating technical documentation, one of our goals is to set up standards for future developers. Thank you for helping us find this glitch.
> 
> If this sounds good, let's change it to 擬似事件 then? :)

I think 擬似事件 is an improvement... now 擬似 has the meaning of imitated, simulated, emulated, virtual, made to look real... so something, you'd think it is exactly the same as before, but just emulated.  Such as the case of a virtual machine, or emulated Nintendo Gamecube... they are exactly the same as before and you can't even tell the difference, only that it is "emulated" or "simulated".  The synthetic event in React is not exactly the same as before.  合成 also has the meaning of synthesize, but it also has a meaning of "put together by smaller items".

Yeah, I think "Synthetic 事件" has the advantage that it can keep it in the original technical term, or "擬似事件", kind of close, but not quite, but does have an improvement.

**Comment by chloewlin** [comment]
Ok, sounds like we can keep it as "synthetic 事件". Can you update the changes and push them up again? Thanks!

**Comment by KennethKinLum** [comment]
> Ok, sounds like we can keep it as "synthetic 事件". Can you update the changes and push them up again? Thanks!

yup, just changed and saved.

**Pull request merged**
