### PR TITLE
Making the translation more specific and readable 這個指南大部分的範例都像這樣可以編輯

### PR DESCRIPTION
**Pull request by KennethKinLum**

### CODE REVIEW

**Comment by vrabe** [comment]
It can also be `這個指南大部分的範例都可以像這樣編輯`.

**Comment by KennethKinLum** [comment]
> It can also be `這個指南大部分的範例都可以像這樣編輯`.

this actually sounds better... can I edit right here instead of starting another new pull request?

**Comment by vrabe** [comment]
I think you can just edit here.

**Comment by vrabe** [comment]
I thought @KennethKinLum would make a commit to edit it?

**Comment by neighborhood999** [comment]
@vrabe this PR is pending for a long time so I think it can be merged, feel free create another PR to update this, thank you.

**Pull request merged**
